version: 35
jobs:
- name: Build jar
  jobExecutor: mainworker
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Gradle Build
    runInContainer: true
    image: gradle:jdk17-alpine
    interpreter: !DefaultInterpreter
      commands: |
        gradle build
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Jar
    artifacts: build/libs/*.jar
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestMergeTrigger
    branches: '*'
    paths: src/main/ build.gradle gradle.properties
    projects: WoldsVaultOfficialMod
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Github Mirror
  jobExecutor: mainworker
  steps:
  - !PushRepository
    name: Github Push
    remoteUrl: https://github.com/iwolfking/Wolds-Vaults-Official-Mod
    userName: iwolfking
    passwordSecret: github_access_token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Github Pull Changes
  jobExecutor: mainworker
  steps:
  - !PullRepository
    name: Github Pull
    remoteUrl: https://github.com/iwolfking/Wolds-Vaults-Official-Mod
    userName: iwolfking
    passwordSecret: github_access_token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 1 * * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
